# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=9, verbose_name='Chave')),
                ('categoria', models.CharField(choices=[('Agente de Crédito', 'Agente de Crédito'), ('Auxiliar Administrativo', 'Auxiliar Administrativo')], max_length=40, verbose_name='Categoria')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('linha', models.IntegerField(default='0000', verbose_name='Linha')),
                ('convenio', models.CharField(max_length=100, verbose_name='Convênio')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(max_length=50, verbose_name='Operação')),
                ('data', models.DateField(default=datetime.date.today)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('troco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prazo', models.IntegerField(verbose_name='Prazo')),
                ('estado', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Cancelado', 'Cancelado'), ('Liberado', 'Liberado')], max_length=20, verbose_name='Estado')),
                ('agencia', models.IntegerField(default='0000', verbose_name='Agência')),
                ('loja', models.IntegerField(default='0000', verbose_name='Loja')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Funcionario', verbose_name='Vendedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Produto', verbose_name='Produto')),
            ],
        ),
    ]
