# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 22:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='categoria',
            field=models.CharField(choices=[('AGT', 'Agente de Crédito'), ('ADM', 'Auxiliar Administrativo')], max_length=40, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='estado',
            field=models.CharField(choices=[('AG', 'Aguardando'), ('CN', 'Cancelado'), ('LB', 'Liberado')], max_length=20, verbose_name='Estado'),
        ),
    ]
